# Generated by Django 3.1.4 on 2021-01-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
